cc_library(
    name = "rectangleLib",
    srcs = ["rectangle.cpp"],
    hdrs = ["inc/rectangle.hpp"],
    deps = [
        "//project/cli/shape:shapeLib"
    ],
    visibility = ["//visibility:public"],
)
