cc_binary(
    name = "finalBinary",
    srcs = ["main.cpp"],
    deps = [
        "//project/cli/shape:shapeLib",
        "//project/cli/rectangle:rectangleLib",
        "//project/cli/circle:circleLib",
    ],
)